apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busylogs
  name: busylogger-app
  namespace: busylogger
spec:
  containers:
  - name: busylogs-httpd
    command: ["/bin/sh", "-c"]    
    args:
      - httpd -f -p 8280 -h /var/www/ ;
      - cat /etc/config/index.html > /var/www/index.html
    image: busybox
    ports:
    - containerPort: 8280
    resources: {}
    volumeMounts:
    - name: wwwroot
      mountPath: /var/www
    - name: busybox-httpd
      mountPath: /etc/config
      subPath: index.html
    - name: logdir
      mountPath: /var/log
      readOnly: true
  - name: busypods-client
    command: ["/bin/sh", "-c"]
    args:  
    - tail -f $(find /var/log/pods -type f -name "*.log" | tr '\n' ' ') >> /var/www/pod-logs.txt
    image: busybox
    resources: {}
    volumeMounts:
    - name: wwwroot
      mountPath: /var/www/
    - name: logdir
      mountPath: /var/log
      readOnly: true
  - name: busyconts-client
    command: ["/bin/sh", "-c"]
    args:
    - tail -f $(find /var/log/containers -type f -name "*.log" | tr '\n' ' ') >> /var/www/container-logs.txt
    image: busybox
    resources: {}
    volumeMounts:
    - name: wwwroot
      mountPath: /var/www
    - name: logdir
      mountPath: /var/log
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: busybox-httpd
    configMap: 
      name: busybox-httpd-config
      items:
      - key: index.html
        path: index.html
  - name: wwwroot
    hostPath:
      path: /var/volumes/busylogger/www
      type: "DirectoryOrCreate"
  - name: logdir
    hostPath: 
      path: /var/log


