apiVersion: v1
kind: Namespace
metadata:
  name: test-busybox
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-busybox
  name: busybox
  namespace: test-busybox
spec:
  containers:
  - name: httpd
    command: ["/bin/sh", "-c"]
    args: 
    image: busybox
    ports:
    - containerPort: 8280
  - name: client-container
    image: busybox
    command: ["sh", "-c"]
    args:
    - while true; do
        echo -en '\n' >> /var/www/pcinfo.txt ;
        if [[ -e /etc/podinfo/labels ]]; then
          echo -en '\n\n'; cat /etc/podinfo/labels >> /var/www/pcinfo.txt ; fi;
        if [[ -e /etc/podinfo/annotations ]]; then
          echo -en '\n\n'; cat /etc/podinfo/annotations >> /var/www/pcinfo.txt ; fi;        
        if [[ -e /etc/podinfo/cpu_limit ]]; then
          echo -en '\n'; cat /etc/podinfo/cpu_limit >> /var/www/pcinfo.txt ; fi;
        if [[ -e /etc/podinfo/cpu_request ]]; then
          echo -en '\n'; cat /etc/podinfo/cpu_request >> /var/www/pcinfo.txt ; fi;
        if [[ -e /etc/podinfo/mem_limit ]]; then
          echo -en '\n'; cat /etc/podinfo/mem_limit >> /var/www/pcinfo.txt ; fi;
        if [[ -e /etc/podinfo/mem_request ]]; then
          echo -en '\n'; cat /etc/podinfo/mem_request >> /var/www/pcinfo.txt ; fi;
        sleep 5;
      done;
    volumeMounts:
      - name: wwwroot
        mountPath: /var/www
      - name: podinfo
        mountPath: /etc/podinfo
      - name: test-busybox-httpd
        mountPath: /etc/config/httpd
      - name: test-busybox-client-container
        mountPath: /etc/config/client
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: wwwroot
    hostPath:
      path: /var/volumes/test-busybox/www
      type: "DirectoryOrCreate"
  - name: test-busybox-httpd
    configMap: 
      name: test-busybox-httpd-config
  - name: test-busybox-client-container
    configMap: 
      name: test-busybox-client-container-config
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations

---
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Container and Pod level logs</title>
</head>
<body>
<h1>Logs from containers</h1>
<embed src="container-logs.txt" type="text/plain" width="300" height="200">
</body>
<body>
<h1>Logs from pods</h1>
<embed src="pod-logs.txt" type="text/plain" width="300" height="200">
</body>
</html>