apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
  namespace: test-busybox
spec:
  containers:
  - args:
    - sh
    - -c
    - echo 'Hello' > /var/www/index.html && httpd -f -p 8280 -h /var/www/
    image: busybox
    name: busybox
    ports:
    - containerPort: 8280
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  